import Head from "next/head";
import Image from "next/image";
import { Open_Sans } from "next/font/google";

import styles from "binar/styles/Home.module.css";
import InputEmail from "binar/components/atoms/InputComponent";
import InputGroup from "binar/components/molecules/InputGroup";
import FormAction from "binar/components/organisms/Form";

const opensans = Open_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Profiln</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo/Icon Binar.svg" />
      </Head>
      <FormAction />
    </>
  );
}
