import React from "react";
import { causten } from "binar/helpers/fontTheme";
import Head from "next/head";
type AppShellProps = {
  children: React.ReactNode;
};

const Layouts = (props: AppShellProps) => {
  const { children } = props;

  return (
    <>
      <Head>
        <title>Profiln</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo/Icon Binar.svg" />
      </Head>
      <main className={`${causten.className} `}>{children}</main>;
    </>
  );
};

export default Layouts;
